development:
  adapter: postgresql
  database: sicko-dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: sicko-test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sicko-prod
  pool: 5
  timeout: 5000
